[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = 'test'
script = 'script'
cache_path = 'cache'
optimizer = true

# required by upgradability
# see: https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

# forces recompilation, required by Upgradable contracts
force = true

# fs permissions for deployment (false by default)
fs_permissions = [
    { access = "read", path = "out" },
    { access = "read-write", path = "deployment" },
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
